apiVersion: apps/v1
kind: Deployment
metadata:
  name: axon-demo-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: axon-demo-ui
  template:
    metadata:
      labels:
        app: axon-demo-ui
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: frontend
        image: okteto.dev/axon-demo-ui:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 250m
            memory: "384Mi"
          limits:
            cpu: "500m"
            memory: "1024Mi"
        ports:
          - name: http
            containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: axon-demo-ui
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    app: axon-demo-ui
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 8080
    - name: debug
      port: 5106
      protocol: TCP
      targetPort: 5005
  selector:
    app: axon-demo-ui