kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: axon-data
  labels:
    app: axonserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
#  storageClassName: ""

