apiVersion: v1
kind: Service
metadata:
  name: axonserver-gui
  labels:
    app: axonserver
spec:
  ports:
    - name: gui
      port: 8024
      targetPort: 8024
  selector:
    app: axonserver
  type: LoadBalancer